version: "3.9"
services:
    api:
        build: .
        depends_on:
            - postgres
        environment:
            DATABASE_URL: postgres://admin@admin1234:5432/db
            NODE_ENV: development
            PORT: 9000
        ports:
            - "9000:9000"
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin1234
            POSTGRES_DB: db
        ports:
            - "5432:5432"
    adminer:
        image: adminer
        depends_on:
            - postgres
        ports:
            - "8080:8080"